import { describe, expect, it, vi } from 'vitest';
import { ReceiptFieldRuleClient } from './receiptFieldRuleClient';
import type { ReceiptBatchInvoke } from './receiptBatchClient';
import { syntheticSnapshot } from '../domain/receiptGrouping.testFixtures';
import type { FieldRuleOperation } from '../domain/receiptFieldRules';
import { parseLocalFieldRule } from '../domain/receiptFieldRules';
import deactivationFixture from './fixtures/fieldRuleDeactivation.json';

const operation = (overrides: Partial<FieldRuleOperation> = {}): FieldRuleOperation => ({ operation_id: 'operation-test', status: 'preparing', total: 451, completed: 0, eligible: 451, skipped: 0, changed: 0, unresolved: 0, can_save_rule: false, rule_id: null, ...overrides });
const ok = (data: unknown) => ({ status: 'ok', data });
describe('读取规则客户端', () => {
  it('通过batch_command发送受限区域及版本，每次步骤延续进度，整批一次apply', async () => {
    const header = syntheticSnapshot(451).header;
    const transport = vi.fn().mockResolvedValueOnce(ok(operation())).mockResolvedValueOnce(ok(operation({ completed: 50 }))).mockResolvedValueOnce(ok({ header: { ...header, grouping_revision: header.grouping_revision + 1 }, operation: operation({ status: 'applied', completed: 451 }) }));
    const client = new ReceiptFieldRuleClient(transport as ReceiptBatchInvoke);
    const prepared = await client.prepare(header, { prototype_segment_id: 'a'.repeat(64), mode: 'direct', fields: [{ role: 'counterparty', field: 'name', rect: { x0: 0.1, y0: 0.1, x1: 0.8, y1: 0.3 } }], include_resolved: false });
    const stepped = await client.step(header.job_id, prepared); expect(stepped.completed).toBe(50);
    await client.apply(header, prepared.operation_id, false, '');
    expect(transport.mock.calls[0][0]).toBe('batch_command');
    expect(transport.mock.calls[0][1].request).toMatchObject({ expected_grouping_revision: header.grouping_revision, expected_review_fingerprint: header.review_fingerprint });
    expect(transport.mock.calls[1][1].request).toMatchObject({ offset: 0, limit: 50 });
    expect(transport.mock.calls[2][1].request).toMatchObject({ op: 'batch_receipt_field_rule_apply', save_rule: false });
    expect(JSON.stringify(transport.mock.calls)).not.toContain('source_path');
  });
  it('拒绝串操作响应与越界分页/输出路径', async () => {
    const transport = vi.fn().mockResolvedValueOnce(ok(operation({ operation_id: 'another' }))).mockResolvedValueOnce(ok({ operation: operation({ status: 'ready', completed: 451 }), items: [], next_offset: 3 }));
    const client = new ReceiptFieldRuleClient(transport as ReceiptBatchInvoke);
    await expect(client.step('job', operation())).rejects.toThrow();
    await expect(client.page('job', 'operation-test')).rejects.toThrow();
    await expect(client.exportDiagnostics(syntheticSnapshot().header, 'b'.repeat(32), '../private')).rejects.toThrow();
  });
  it('停用遵循后端不可变规则版本合同：active改变而revision不变', async () => {
    // Generated by actual FieldRuleStore.create/deactivate + receipt_field_rule_api.public_rule,
    // with tests/test_receipt_field_rule_store.py's synthetic definition and in-memory SQLite.
    const rule = parseLocalFieldRule(deactivationFixture.before);
    const transport = vi.fn().mockResolvedValueOnce(ok(deactivationFixture.after)).mockResolvedValueOnce(ok({ ...rule, revision: rule.revision + 1, active: false }));
    const client = new ReceiptFieldRuleClient(transport as ReceiptBatchInvoke);
    expect(await client.deactivate(rule)).toEqual({ ...rule, active: false });
    expect(transport.mock.calls[0][1].request).toEqual({ op: 'batch_receipt_field_rule_deactivate', rule_id: rule.rule_id, expected_revision: rule.revision });
    await expect(client.deactivate(rule)).rejects.toThrow();
  });
});
