[CmdletBinding()]
param(
    [ValidateSet('Core', 'Ocr')][string]$Edition = 'Core',
    [switch]$Rebuild
)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
$projectRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$buildRoot = Join-Path $projectRoot '.build'
$runtimeRoot = Join-Path $buildRoot 'runtime'
$pythonRoot = Join-Path $runtimeRoot 'python'
$marker = Join-Path $runtimeRoot '.generated-runtime'
$manifest = Get-Content -LiteralPath (Join-Path $PSScriptRoot 'runtime-manifest.json') -Raw | ConvertFrom-Json
$lockName = 'requirements-' + $Edition.ToLowerInvariant() + '-win-x64.lock'
$lockFile = Join-Path $projectRoot ('engine/' + $lockName)
function Assert-OrdinaryDirectory([string]$Directory) {
    if (Test-Path -LiteralPath $Directory) {
        $item = Get-Item -LiteralPath $Directory -Force
        if (-not $item.PSIsContainer -or ($item.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
            throw 'Build paths must be ordinary directories, not links or junctions.'
        }
    }
}
foreach ($directory in @($projectRoot, $buildRoot, $runtimeRoot, (Join-Path $buildRoot 'downloads'), (Join-Path $buildRoot 'wheels'))) {
    Assert-OrdinaryDirectory $directory
}
if (-not (Test-Path -LiteralPath $lockFile -PathType Leaf)) { throw "Missing release lock: $lockName" }
if (-not [Environment]::Is64BitOperatingSystem -or $env:PROCESSOR_ARCHITECTURE -eq 'ARM64') {
    throw 'Release runtime preparation requires Windows x64.'
}
New-Item -ItemType Directory -Force -Path $buildRoot | Out-Null
if (Test-Path -LiteralPath $runtimeRoot) {
    if (-not $Rebuild) { throw 'Runtime already exists. Use -Rebuild to regenerate this build output.' }
    # Delete only our marked, generated directory inside this checkout.
    $resolved = (Resolve-Path -LiteralPath $runtimeRoot).Path
    if ($resolved -ne [IO.Path]::GetFullPath($runtimeRoot) -or
        -not $resolved.StartsWith($projectRoot + [IO.Path]::DirectorySeparatorChar, [StringComparison]::OrdinalIgnoreCase) -or
        -not (Test-Path -LiteralPath $marker -PathType Leaf) -or
        ((Get-Item -LiteralPath $runtimeRoot).Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw 'Refusing to remove an unrecognized runtime directory.'
    }
    if (Get-ChildItem -LiteralPath $runtimeRoot -Recurse -Force | Where-Object { $_.Attributes -band [IO.FileAttributes]::ReparsePoint } | Select-Object -First 1) {
        throw 'Refusing to remove a runtime that contains links or junctions.'
    }
    Remove-Item -LiteralPath $runtimeRoot -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $runtimeRoot | Out-Null
Set-Content -LiteralPath $marker -Value 'Generated by scripts/prepare-runtime.ps1' -Encoding utf8
$downloadRoot = Join-Path $buildRoot 'downloads'
New-Item -ItemType Directory -Force -Path $downloadRoot | Out-Null
$archive = Join-Path $downloadRoot 'python.tar.gz'
if (-not (Test-Path -LiteralPath $archive)) {
    Invoke-WebRequest -Uri $manifest.python.url -OutFile ($archive + '.partial') -UseBasicParsing
    Move-Item -LiteralPath ($archive + '.partial') -Destination $archive
}
if ((Get-FileHash -LiteralPath $archive -Algorithm SHA256).Hash -ne $manifest.python.sha256) {
    throw 'Python archive checksum mismatch; refusing to execute downloaded code.'
}
& tar -xzf $archive -C $runtimeRoot
if ($LASTEXITCODE -ne 0) { throw 'Python extraction failed.' }
$python = Join-Path $pythonRoot 'python.exe'
if (-not (Test-Path -LiteralPath $python -PathType Leaf)) { throw 'Python executable missing after extraction.' }
function Invoke-PrivatePip([string[]]$PipArguments) {
    $previousConfig = [Environment]::GetEnvironmentVariable('PIP_CONFIG_FILE', 'Process')
    try {
        # -I isolates Python; pip also needs its own environment/config isolation.
        $env:PIP_CONFIG_FILE = 'nul'
        & $python -B -I -m pip --isolated @PipArguments
        if ($LASTEXITCODE -ne 0) { throw 'Private runtime pip command failed.' }
    } finally {
        [Environment]::SetEnvironmentVariable('PIP_CONFIG_FILE', $previousConfig, 'Process')
    }
}
& $python -B -I -c 'import sys; assert sys.version_info[:3] == (3,12,14); assert sys.maxsize > 2**32'
if ($LASTEXITCODE -ne 0) { throw 'Python version/architecture validation failed.' }
$wheelCache = Join-Path $buildRoot 'wheels'
New-Item -ItemType Directory -Force -Path $wheelCache | Out-Null
$requiredHashes = @(Select-String -LiteralPath $lockFile -Pattern '--hash=sha256:([a-f0-9]{64})' -AllMatches | ForEach-Object { $_.Matches } | ForEach-Object { $_.Groups[1].Value })
$cachedHashes = @(Get-ChildItem -LiteralPath $wheelCache -File -Filter '*.whl' | Get-FileHash -Algorithm SHA256 | ForEach-Object { $_.Hash.ToLowerInvariant() })
$missingHashes = @($requiredHashes | Where-Object { $_ -notin $cachedHashes })
if ($missingHashes.Count -eq 0) {
    Invoke-PrivatePip @('download', '--no-index', '--find-links', $wheelCache, '--only-binary=:all:', '--require-hashes', '--dest', $wheelCache, '-r', $lockFile, '--disable-pip-version-check')
} else {
    Invoke-PrivatePip @('download', '--only-binary=:all:', '--require-hashes', '--dest', $wheelCache, '-r', $lockFile, '--disable-pip-version-check')
}
Invoke-PrivatePip @('install', '--no-index', '--find-links', $wheelCache, '--require-hashes', '-r', $lockFile, '--disable-pip-version-check', '--no-compile')
Invoke-PrivatePip @('check')
& $python -B -I (Join-Path $PSScriptRoot 'runtime-inventory.py') --output (Join-Path $pythonRoot 'runtime-info.json') --edition $Edition --manifest (Join-Path $PSScriptRoot 'runtime-manifest.json') --lock $lockFile
if ($LASTEXITCODE -ne 0) { throw 'Runtime inventory generation failed.' }
& $python -B -E -s -X utf8 (Join-Path $projectRoot 'engine/engine.py') --health
if ($LASTEXITCODE -ne 0) { throw 'Bundled engine health check failed.' }
# Console launchers contain build-machine paths and are unused by the app.
# Only remove generated files below this verified extraction root.
$generatedScripts = Join-Path $pythonRoot 'Scripts'
if (Test-Path -LiteralPath $generatedScripts) { Remove-Item -LiteralPath $generatedScripts -Recurse -Force }
Get-ChildItem -LiteralPath $pythonRoot -Recurse -File -Filter '*.pyc' | Remove-Item -Force
Write-Output "Prepared $Edition runtime: $pythonRoot"
